import { type Report } from '../report/store';
import { IDK } from './store';

export const fakeData: Report = {
  id: 1,
  locked: true,
  title: 'Test report',
  type: 'Incident Report',
  notes:
    '<h2 style="text-align: center">Don Morello | Bank Robbery </h2><p>On 7/16/23, Don Morello entered legion square banking with an M16 Semi Automatic Rifle and proceeded to to fire 12 rounds into a group of individuals, 4 of the 6 individuals were found DEAD and 2 injured with GSWs on scene as Law Enforcement and Swat arrived</p>',
  offenders: [
    {
      citizenid: '1039',
      firstname: 'carter',
      lastname: 'zamgato',
      warrant: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 7).toString(),
      charges: [
        {
          charge: {
            id: 0,
            title: 'Test Charge',
            description: 'Test Charge Description',
            fine: '250',
            months: '2',
            type: '1',
          },
          count: 1,
        },
      ],
    },
  ],
  officers: [
    {
      citizenid: '4913',
      firstname: 'don',
      lastname: 'morello',
      callsign: '153',
      department: 'lspd',
      rank: 1,
    },
    {
      citizenid: '1039',
      firstname: 'carter',
      lastname: 'zamgato',
      callsign: '153',
      department: 'lspd',
      rank: 1,
    },
  ],
<<<<<<< HEAD
  gallery: ['https://i.imgur.com/4QX7X2o.png'],
=======
  gallery: [{ url: 'https://i.imgur.com/4QX7X2o.png', notes: 'test' }],
>>>>>>> 2b921bce8915dc91717b2f9bd749a5044c62e40e
  updatedAt: new Date().toString(),
  createdAt: new Date().toString(),
};

export const fakeSearchData: IDK[] = [
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
  {
    id: 1,
    title: 'Test report',
    locked: true,
    type: '2',
    citizenid: '4913',
    firstname: 'carter',
    lastname: 'zamgato',
    callsign: '153',
    createdAt: new Date().toString(),
  },
];
