import {
  HomeIcon,
  UsersIcon,
  ScrollTextIcon,
  CarIcon,
  ScaleIcon,
  ShieldIcon,
  MapPinIcon,
  Loader2Icon,
  Settings,
  UserIcon,
  LogOutIcon,
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  StrikethroughIcon,
  XIcon,
  HighlighterIcon,
  QuoteIcon,
  AlignRightIcon,
  AlignLeftIcon,
  AlignJustifyIcon,
  AlignCenterIcon,
  ArrowRightIcon,
  Navigation,
  RadioTowerIcon,
  Briefcase,
  CakeIcon,
  EyeOffIcon,
  MoreHorizontal,
  PhoneIcon,
  PlusIcon,
  Minus,
  XCircleIcon,
  XSquareIcon,
  XOctagonIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronUpIcon,
  ChevronsUpDownIcon,
  ChevronsLeftIcon,
  ChevronsRightIcon,
  CheckIcon,
  DotIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  Heading4Icon,
  Heading5Icon,
  Heading6Icon,
  LockIcon,
  CalendarIcon,
  UnlockIcon,
  BuildingIcon,
  HashIcon,
  RefreshCcwDotIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  FileClockIcon,
  SlidersHorizontalIcon,
  SearchIcon,
  type LucideProps,
  type LucideIcon as LucidIcon,
} from 'lucide-react';

export type Icon = LucidIcon;

export const Icons = {
  home: HomeIcon,
  users: UsersIcon,
  reports: ScrollTextIcon,
  vehicles: CarIcon,
  dispatch: MapPinIcon,
  legislation: ScaleIcon,
  roster: ShieldIcon,
  logs: FileClockIcon,
  settings: Settings,
  loading: Loader2Icon,
  user: UserIcon,
  logout: LogOutIcon,
  bold: BoldIcon,
  italic: ItalicIcon,
  underline: UnderlineIcon,
  strike: StrikethroughIcon,
  highlight: HighlighterIcon,
  blockquote: QuoteIcon,
  hr: Minus,
  alignRight: AlignRightIcon,
  alignLeft: AlignLeftIcon,
  alignJustify: AlignJustifyIcon,
  alignCenter: AlignCenterIcon,
  close: XIcon,
  radioTower: RadioTowerIcon,
  navigation: Navigation,
  arrowRightLeft: ArrowRightIcon,
  car: CarIcon,
  caroff: (props: LucideProps) => (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      strokeWidth='2'
      stroke='currentColor'
      fill='none'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path stroke='none' d='M0 0h24v24H0z' fill='none'></path>
      <path d='M7 17m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0'></path>
      <path d='M15.584 15.588a2 2 0 0 0 2.828 2.83'></path>
      <path d='M5 17h-2v-6l2 -5h1m4 0h4l4 5h1a2 2 0 0 1 2 2v4m-6 0h-6m-6 -6h8m4 0h3m-6 -3v-2'></path>
      <path d='M3 3l18 18'></path>
    </svg>
  ),
  briefcase: Briefcase,
  cake: CakeIcon,
  eyeOff: EyeOffIcon,
  moreHorizontal: MoreHorizontal,
  phone: PhoneIcon,
  plus: PlusIcon,
  minus: Minus,
  xCircle: XCircleIcon,
  xSquare: XSquareIcon,
  xOctagon: XOctagonIcon,
  chevronDown: ChevronDownIcon,
  chevronRight: ChevronRightIcon,
  chevronLeft: ChevronLeftIcon,
  chevronUp: ChevronUpIcon,
  chevronsUpDown: ChevronsUpDownIcon,
  chevronsLeft: ChevronsLeftIcon,
  chevronsRight: ChevronsRightIcon,
  check: CheckIcon,
  dot: DotIcon,
  h1: Heading1Icon,
  h2: Heading2Icon,
  h3: Heading3Icon,
  h4: Heading4Icon,
  h5: Heading5Icon,
  h6: Heading6Icon,
  lock: LockIcon,
  unlock: UnlockIcon,
  calendar: CalendarIcon,
  building: BuildingIcon,
  hash: HashIcon,
  folderSync: RefreshCcwDotIcon,
  arrowDown: ArrowDownIcon,
  arrowUp: ArrowUpIcon,
  slidersHorizontal: SlidersHorizontalIcon,
  search: SearchIcon,
};
